name: Fivetran
config-version: 2
version: 2.0.0

# Configure the models in models/facts/ to be materialized as views
# in development and tables in production/CI contexts

models:
  Fivetran:
    facts:
      +materialized: "{{ 'view' if target.name == 'dev' else 'table' }}"